- name: Building Image
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/base.yml
  become: true
  become_user: root
  remote_user: root
  tasks:
    - name: Build And Install
      tags: build
      include_tasks:
        file: "jobs/build/{{item}}.yml"
        apply:
          tags:
            - build
      loop:
        - prep
        - nodejs
        - rbenv
        - rubyrails
        - passenger
