---
- name: PROJECT NAME
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build And Install
      tags: build
      include_tasks:
        file: "jobs/build/{{item}}.yml"
        apply:
          tags:
            - build
      loop:
        - prep
        - nodejs
        - rbenv
        - rubyrails
        - passenger

    - name: Run And Configure
      tags: run
      include_tasks:
        file: jobs/run/run.yml


