---
- name: PROJECT NAME
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Run And Configure
      include_tasks:
        file: jobs/run/run.yml
    - name: Execute application
      include_tasks:
        file: jobs/run/exec.yml
    - name: Run tests to make sure app is running as expected
      include_tasks:
        file: jobs/tests/tests.yml
