---
- name: BarCitizen Core
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build And Install
      tags: build
      include_tasks:
        file: "jobs/build/{{ job_name }}.yml"
        apply:
          tags:
            - build
      loop:
        - prep
        - nodejs
        - easybutton
        - passenger
        - security
      loop_control:
        loop_var: job_name
#    - name: Run And Configure
#      tags: run
#      include_tasks:
#        file: jobs/run/run.yml
