run:
  user: root
app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE', default='RUBY') }}"
node:
  version: "{{ lookup('ansible.builtin.env', 'NODE_VERSION', default='20') }}"
  key_url: "{{ lookup('ansible.builtin.env', 'NODE_KEYURL', default='https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key') }}"
ruby:
  dir: /root/.rbenv
  version: "{{ lookup('ansible.builtin.env', 'RUBY_VERSION', default='3.2.2') }}"
  installer:
    version: "{{ lookup('ansible.builtin.env', 'RUBY_INSTALLER_VERSION', default='0.9.3') }}"
rails:
  version: "{{ lookup('ansible.builtin.env', 'RAILS_VERSION', default='7.0.4') }}"
